# Site Settings
baseurl: ""
url : "https://E-RROR.github.io"

# Blog Settings
theme_settings :
  title : Sina Farhadi | سینا فرهادی
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/avatar.jpeg
    username : سینا فرهادی
    description : یه پسر که بلاکچین و یادگیری ماشینی دوست داره
    experience :
      - start : 2018-01-03
        end : *
        experience: Software developing
    skills : 
      - skill : Blockchain & Smart Contracts
        value : 65  # Percent value
      - skill : Machine Learning
        value : 55  # Percent value
      - skill : Software development
        value : 85  # Percent value
      - skill : Agile & Scrum
        value : 75  # Percent value
      - skill : Business Models
        value : 65  # Percent value
      - skill : volition
        value : 100  # Percent value
        
  # Icons
  icons :
    email:
    linkedin: https://www.linkedin.com/in/sina-farhadi-profile/
    github: E-RROR
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:
    stackoverflow: 12712466/sina

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
