# Site Settings
baseurl: ""
url : "https://E-RROR.github.io"

# Blog Settings
theme_settings :
  title : Sina Farhadi | سینا فرهادی
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/Screenshot 2021-04-21 155550.png
    username : سینا فرهادی
    description : یه پسر که با بلاکچین و یادگیری ماشینی دوست داره استارت اپ باحال بسازه
    experience :
      - start : 2020-10-03
        end : life
        experience : یارا تکین افلاک مانلی, بنیانگذار
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:
    linkedin: https://www.linkedin.com/in/sina-farhadi-profile/
    github: E-RROR
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
